### ISSUE TITLE
Can't implament an Inventory system for the player

### ISSUE THREAD

**Issue by MaxIsJoe** [MaxIsJoe/TWCRemake#1]
[https://github.com/MaxIsJoe/TWCRemake/commit/b63cb1079a81cc2267fe764a49c97b309d193037](url)

I tried working on this inventory system for a while now and i gave up for now, I will shift my focus on something else until i find someone who can help me with this

I know that i have my finger on SOMETHING i just don't know how to actually make the Inventory system display items and work correctly.

**Comment by MaxIsJoe** [comment]
The Inventory system now semi-works
Icons for Items show up but at least Items now get listed on the inventory UI.

Next up.. adding functionality to these buttons.
Use, Examine, etc.

**Comment by MaxIsJoe** [comment]
![image](https://user-images.githubusercontent.com/34368774/54438402-435a1680-473f-11e9-9250-49e8a1711d59.png)

The inventory has got an overhaul and is now a bit more functional than the old inventory, still looking into how we can make items usable just like the original game via the right click context menus.

**Comment by BrokenMedjed** [comment]
Cough. I need to start working on this lmao

**Comment by MaxIsJoe** [comment]
After working with godot for quite some time and me remembering that this project still exists, there will be another rework or overhaul or whatever you like to call it to this monstrosity.

Instead of doing whatever younger me was trying to achieve, The inventory system should use JSON to store and load item data from it. This will be simpler, less buggy and will be more easy on memory and networking when the 0.1 alpha comes out, if it ever comes out lol.

The JSON_Loader function already exists since #[I added this today](https://github.com/MaxIsJoe/TWCRemake/commit/3f8e972a373fdc281ef370c7c593b8928aba31f9) so all what needs to be done is to get rid of the absolutely horrible code I wrote and make a JSON file that will contain all items and their data then make a new system that utilizes JSON for displaying and using data.

**Comment by MaxIsJoe** [comment]
![image](https://user-images.githubusercontent.com/34368774/96826297-59f44380-1433-11eb-9323-a7fbc92976b3.png)
Good news, the inventory system now uses JSON, only took me an hour or two to rewrite everything.
This will make adding items to the game much more easier and more customizable in the future and will be great for performance.

There are still a lot of things that needs to be done though, for example, all items cannot be used or equipped because there hasn't been any way to handle item functionality yet. I plan on working on that next then work on NPC shops.

After all the inventory work is done, I think I should go back to working on the maps or networking.
